### ISSUE TITLE
some animal from MorrowRim trolls mod causes error (probably cave troll which appears only when VAE Caves is installed)

### ISSUE THREAD

**Issue by inikishev** [XT-0xFF/CustomizeAnimals#2] opened 2021-09-27 18:57 UTC
https://gist.github.com/HugsLibRecordKeeper/d26414afb74309e68f9becfad3a8a0cb
the error that I am getting doesn't display into the log so 
![image](https://user-images.githubusercontent.com/76593873/134968151-4ef971ef-7ee2-4602-8cf1-df6a1660963f.png)
this happens when I was clicking through trolls in the mod. I didn't notice on which troll it crashed the mod settings window but I think it is on cave troll which only appears with VAE Caves installed, because it also had a problem where some other mods couldn't customize it, and the mod that shows what mod this is from doesn't display what modt he cave troll is from.

**Comment by ChrisF-127** [comment] 2021-09-27 19:44
Found and fixed. Thank you for the report!

The modContentPack for this animal is null, something I should have checked for.
I also went and put in some safety measures to prevent exceptions caused by the animal settings pages from crashing the mod settings window.

Will be included in the next version.

**Closed as completed by ChrisF-127** 2021-09-27 19:44 UTC
